apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8sinstance
spec:
  #serviceName: "k8sinstance"
  replicas: 1
  template:
    metadata:
      labels:
        app: k8sinstance
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      # soft antiaffinity for optimize placement
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution: 
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - k8sinstance
              topologyKey: kubernetes.io/hostname
      containers:
      - name: k8sinstance
        #image: 172.16.155.136:5000/emotibot-k8s/uwebserverv6
        image: 172.16.155.136:5000/k8sinstance:v0.65
        #args: ["-p", "8001"]

        #readinessProbe:
        #  tcpSocket:
        #    port: 8000
        #  initialDelaySeconds: 20
        #  periodSeconds: 5

        stdin: true
        securityContext:
          privileged: true
          capabilities:
             add:
               - NET_ADMIN
        ports:
          - containerPort: 8000
        resources:
          limits:
            cpu: 0.3 
            memory: 256Mi
          requests:
            cpu: 0.3
            memory: 256Mi

        volumeMounts:
        - mountPath: /etc/localtime
          name: hosttime
        - mountPath: /var/log/web
          name: loggerfile
        #serviceAccountName: k8sinstanceagent
      volumes:
       - name: hosttime
         hostPath:
           path: /etc/localtime 
       - name: loggerfile
         hostPath:
           path: /var/log/containerlogger/web
      #select node label if enable
      #nodeSelector:
      #  ebotrole: worker
  minReadySeconds: 5
  strategy:
    # indicate which strategy we want for rolling update
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

---
apiVersion: v1
kind: Service
metadata:
  name: k8sinstance
  labels:
    app: k8sinstance
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    #port is loadbalancer port
    #targetport is container port
    #nodePort is external accessing from any given k8s cluster ip
    port: 8001
    targetPort: 8000
    nodePort: 31809
  selector:
    app: k8sinstance
